import { Geist, Geist_Mono, Instrument_Sans, Instrument_Serif, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ['latin'], 
})

const instrumental = Instrument_Serif({
  variable: "--font-instrument",
  subsets: ["latin"],
  weight: "400"
})

export const metadata = {
  title: "Randall",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${instrumental.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
